[workspace]
resolver = "2"
members = [
    "qail-core",
    "qail-macro",
    "qail-cli",
    "qail-bench",
    "qail-lsp",
    "qail-wasm",
]

[workspace.lints.rust]
warnings = "deny"
unused = "deny"
dead_code = "deny"
unused_imports = "deny"
unused_variables = "deny"
