[workspace]
resolver = "2"
members = [
    "qail-core",
    "qail-macros",
    "qail-cli",
    "qail-bench",
    "qail-lsp",
    "qail-wasm",
    "qail-ffi",
    "qail-sqlx",
]

[workspace.lints.rust]
warnings = "deny"
unused = "deny"
dead_code = "deny"
unused_imports = "deny"
unused_variables = "deny"
