[book]
title = "QAIL Documentation"
authors = ["QAIL Team"]
language = "en"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/qail-rs/qail"
edit-url-template = "https://github.com/qail-rs/qail/edit/main/docs/{path}"
additional-css = ["theme/custom.css"]
