[package]
name = "qail-bench"
version = "0.6.0"
edition = "2021"

[[bench]]
name = "query_benchmark"
harness = false

[dependencies]
qail-core = { path = "../qail-core" }
qail-macro = { path = "../qail-macro" }
criterion = { version = "0.5", features = ["html_reports"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[lints]
workspace = true
