[package]
name = "qail-bench"
version = "0.5.0"
edition = "2021"

[[bench]]
name = "query_benchmark"
harness = false

[dependencies]
qail-core = { path = "../qail-core" }
qail-macro = { path = "../qail-macro" }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
criterion = { version = "0.5", features = ["async_tokio"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
